# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_remove_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Name',
            field=models.CharField(default='t', max_length=200),
        ),
    ]
