# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Ward_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Class',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='Edition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='Phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Publisher',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='Your_District',
            field=models.CharField(max_length=100),
        ),
    ]
