# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Name',
        ),
    ]
