# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Status',
            field=models.CharField(choices=[('O', 'Open'), ('R', 'Reserved')], default='Open', max_length=10),
        ),
    ]
