# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20171205_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Edition',
            field=models.CharField(choices=[('f', 'first'), ('s', 'second'), ('t', 'third'), ('f', 'forth'), ('f', 'fifth'), ('s', 'sixth'), ('s', 'seventh'), ('e', 'eighth'), ('n', 'ninth'), ('t', 'tenth')], default='first', max_length=10),
        ),
    ]
